### ISSUE TITLE
camera_capture_with_opencv ,Cannot read camera

### ISSUE THREAD

**Issue by monkeycc** [Pcothren/DearPyGui-Examples#121]
Thanks for sharing the code

cv.VideoCapture(0)
DearPyGui Cannot read camera

<img width="436" alt="1" src="https://user-images.githubusercontent.com/6490927/168245623-cb2e321d-f744-4b70-b98a-19d91650d88b.png">
<img width="254" alt="2" src="https://user-images.githubusercontent.com/6490927/168245632-188e098c-b1fd-4ab6-add8-c246a95034fd.png">

**Comment by Pcothren** [comment]
It would help if you posted some code on how you are loading the array into DPG 
What type are you loading it as?

**Comment by monkeycc** [comment]
thank you

It's my computer environment

Can use

Thanks for sharing the code, very good program
